apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: power-device-plugin
  namespace: power-device-plugin
  labels:
    app: power-device-plugin
spec:
  selector:
    matchLabels:
      app: power-device-plugin
  template:
    metadata:
      annotations:
        openshift.io/required-scc: privileged
        openshift.io/scc: privileged
      labels:
        app: power-device-plugin
    spec:
      # Dev: we're only installing on workers.
      # tolerations:
      # - key: node-role.kubernetes.io/control-plane
      #   operator: Exists
      #   effect: NoSchedule
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      containers:
      - name: plugin
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        env:
        - name: GHW_CHROOT
          value: "/host/dev"
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: host-sys
          mountPath: /host/sys
        - name: host-dev-plugins
          mountPath: /host/var/lib/kubelet/device-plugins
        serviceAccount: dev-device-plugin
        serviceAccountName: dev-device-plugin
        securityContext:
          privileged: true
          capabilities:
            add:
              - CAP_SYS_ADMIN
              - CAP_FOWNER
              - NET_ADMIN
              - SYS_ADMIN
            drop:
              - ALL
          runAsUser: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
      volumes:
       - name: host-sys
         hostPath:
           path: /sys
           type: Directory
       - name: host-dev-plugins
         hostPath:
           path: /var/lib/kubelet/device-plugins
           type: Directory
      priorityClassName: system-node-critical
      hostPID: true
      hostIPC: true
      hostNetwork: true
      serviceAccount: power-device-plugin
      serviceAccountName: power-device-plugin
  updateStrategy:
    type: RollingUpdate