apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ex-sa-rbac
  namespace: ex-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostmount-anyuid
subjects:
- kind: ServiceAccount
  name: ex-sa
  namespace: ex-device-plugin