apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-device-plugin
  namespace: ex-device-plugin
  labels:
    app: ex-device-plugin
spec:
  selector:
    matchLabels:
      app: ex-device-plugin
  template:
    metadata:
      labels:
        app: ex-device-plugin
    spec:
      containers:
      - name: plugin
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 100Mi
            power-dev-plugin/dev: 1
          requests:
            cpu: 100m
            memory: 100Mi
            power-dev-plugin/dev: 1
        volumeMounts:
        - name: host-mnt
          mountPath: /mnt
        serviceAccount: ex-sa
        serviceAccountName: ex-sa
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
      serviceAccount: ex-sa
      serviceAccountName: ex-sa
      volumes:
       - name: host-mnt
         hostPath:
           path: /mnt
           type: Directory
  updateStrategy:
    type: RollingUpdate