apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-device-plugin
  namespace: ex-device-plugin
  labels:
    app: ex-device-plugin
spec:
  selector:
    matchLabels:
      app: ex-device-plugin
  template:
    metadata:
      labels:
        app: ex-device-plugin
      annotations:
        openshift.io/required-scc: 'hostmount-anyuid'
    spec:
      containers:
      - name: plugin
        image: quay.io/powercloud/ocp4-power-workload-tools:main
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sleep" ]
        args: [ "infinity" ]
        resources:
          limits:
            memory: 100Mi
            power-dev-plugin/dev: 1
          requests:
            cpu: 100m
            memory: 100Mi
            power-dev-plugin/dev: 1
        volumeMounts:
        - name: test-vol
          mountPath: /mnt
        serviceAccount: ex-sa
        serviceAccountName: ex-sa
        securityContext:
          privileged: false
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
      serviceAccount: ex-sa
      serviceAccountName: ex-sa
      volumes:
        - name: test-vol
          hostPath:
            path: /var/demo
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate