apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-test
  namespace: ex-device-plugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: storageclass-tbd
  volumeMode: Filesystem