apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ex-device-plugin

namespace: ex-device-plugin

generatorOptions:
  disableNameSuffixHash: true

resources:
- 01-sa.yaml
- 02-rbac.yaml
- 03-deployment.yaml
