apiVersion: v1
kind: ConfigMap
metadata:
  name: power-device-config
  namespace: power-device-plugin
data:
  config.json: |
    {
      "nx-gzip": true,
      "permissions": "rw",
      "include-devices": ["/dev/dm-*", "/dev/crypto/nx-gzip"],
      "exclude-devices": ["/dev/dm-3"],
      "discovery-strategy": "time",
      "scan-interval": "1m"
    }
