apiVersion: apps/v1
kind: Deployment
metadata:
  name:  power-dev-mutate
  namespace: power-device-plugin
  labels:
    app: power-dev-mutate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: power-dev-mutate
  template:
    metadata:
      labels:
        app: power-dev-mutate
    spec:
      containers:
        - name: power-dev-mutate
          image: quay.io/powercloud/power-dev-plugin:main
          imagePullPolicy: Always
          command: [ "/opt/power-dev-plugin/bin/power-dev-webhook" ]
          args:
            - 2>&1
          ports:
          - containerPort: 8080
            name: http
          volumeMounts:
            - name: power-dev-mutate-config
              mountPath: /etc/power-dev-mutate/
              readOnly: true
      volumes:
        - name: power-dev-mutate-config
          configMap:
            name: power-dev-mutate-cm
      priorityClassName: system-cluster-critical