apiVersion: v1
kind: Service
metadata:
  name: mutate-webhook-svc
  namespace: power-device-plugin
  labels:
    app: power-dev-mutate
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: power-dev-mutate