apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: power-device-plugin
  namespace: power-device-plugin

resources:
  - 00-configmap.yaml
  - 01-deployment.yaml
  - 02-service.yaml
  - webhook_configuration.yaml

sortOptions:
  order: fifo
